### ISSUE TITLE
3D selection doesn't work on macOS

### ISSUE THREAD

**Issue by nikmolnar** [VISTAS-IVES/pyvistas#35]
The `MeshRenderable.render_for_selection_hit` causes the following error on mac:

```
Traceback (most recent call last):
  File "/Users/nikmolnar/projects/pyvistas/source/vistas/ui/controls/viewer_panel.py", line 310, in OnCanvasDClick
    object = self.gl_canvas.camera.select_object(*size, event.GetX(), event.GetY())
  File "/Users/nikmolnar/projects/pyvistas/source/vistas/core/graphics/camera.py", line 162, in select_object
    object = self.scene.select_object(self, x, y)
  File "/Users/nikmolnar/projects/pyvistas/source/vistas/core/graphics/scene.py", line 72, in select_object
    obj.render_for_selection_hit(camera, r, g, b)
  File "/Users/nikmolnar/projects/pyvistas/source/vistas/core/graphics/mesh_renderable.py", line 64, in render_for_selection_hit
    glDrawElements(self.mesh.mode, self.mesh.num_indices, GL_UNSIGNED_INT, None)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6561)
  File "wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6439)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
    err = 1282,
    description = b'invalid operation',
    baseOperation = glDrawElements,
    pyArgs = (
        GL_TRIANGLES,
        2511528,
        GL_UNSIGNED_INT,
        None,
    ),
    cArgs = (
        GL_TRIANGLES,
        2511528,
        GL_UNSIGNED_INT,
        None,
    ),
    cArguments = (
        GL_TRIANGLES,
        2511528,
        GL_UNSIGNED_INT,
        None,
    )
)
```

**Comment by TaylorMutch** [comment]
This seems to be caused by the lack of a vertex array object being bound when performing the `render_for_selection_hit`. Using vertex array objects is required when using core profile. On Windows we can get away with it because there is a (deprecated, but still not removed in Windows) default vertex array object.

https://stackoverflow.com/questions/30057286/how-to-use-vbos-without-vaos-with-opengl-core-profile

**Comment by nikmolnar** [comment]
This seems to no longer be a problem.

**Comment by TaylorMutch** [comment]
#64 resolved this I believe. Core profile requires vertex and fragment shader, I believe.

**Comment by TaylorMutch** [comment]
Err, #63.
